version: '3.3'

services:
  mariadb_asalek:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
  nginx_asalek:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    depends_on:
      - mariadb_asalek
        # condition: service_healthy

  #restart : no always on-failure unless-stopped
  