version: '3.3'

volumes:
  mariadb_V:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/asalek/data/maria_v'
    labels:
      my_label: 'mariaDb_v'
  wordpress_V:
    driver: local
    driver_opts:
      type: 'none' #no storage driver should be used for this volume
      o: 'bind'
      device: '/home/asalek/data/wordpress_v'
    labels:
      my_label: 'wordPress_v'
  nmap_V:
    driver: local
    driver_opts:
      type: 'none' #no storage driver should be used for this volume
      o: 'bind'
      device: '/home/asalek/data/nmap_v'
    labels:
      my_label: 'nmap_v'

networks:
  i-network:
    ipam:
      driver: default
      config:
      - subnet: 13.37.0.1/16

services:
  mariadb_asalek:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb_V:/var/lib/mysql #/home/login/data
    restart: always
    env_file:
      - .env
    networks:
      - i-network
  nginx_asalek:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress_asalek
    networks:
      - i-network
    env_file:
      - ./.env
    volumes:
      - wordpress_V:/var/www/html
  wordpress_asalek:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_V:/var/www/html
    depends_on:
      - mariadb_asalek
    networks:
      - i-network
  tindog:
    image: tindog:1337
    container_name: tindog
    build: ./bonus/web/
    ports:
      - 1337:1337
    networks:
      - i-network
    restart: unless-stopped
  nmap:
    volumes:
      - nmap_V:/scan_result/
    image: nmap:pen
    container_name: nmap
    build: ./bonus/nmap/
    networks:
      - i-network
    restart: unless-stopped
  redis:
    image: redis
    container_name: redis
    build: ./bonus/redis/
    volumes:
      - wordpress_V:/var/www/html
    networks:
      - i-network
    depends_on:
      - wordpress_asalek
    restart: unless-stopped
  adminer:
    image: adminer
    container_name: adminer
    build: ./bonus/adminer/
    networks:
      - i-network
    ports:
      - 1025:1025
    depends_on:
      - mariadb_asalek
    restart: unless-stopped
  ftp:
    image: ftp
    container_name: ftp
    build: ./bonus/ftp/
    networks:
      - i-network
    ports:
      - "21:21"
      - "20000-20010:20000-20010"
    depends_on:
      - wordpress_asalek
    env_file:
      - .env
    volumes:
      - wordpress_V:/var/www/html
    restart: unless-stopped
  #restart : no always on-failure unless-stopped