version: '3.3'

volumes:
  mariadb_V:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/asalek/maria_v'
    labels:
      my_label: 'mariaDb_v'

networks:
  i-network:
    ipam:
      driver: default
      config:
      - subnet: 13.37.0.1/16

services:
  mariadb_asalek:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb_V:/tmp/ #/home/login/data
    restart: always
    env_file:
      - .env
    networks:
      - i-network
  nginx_asalek:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - mariadb_asalek
    networks:
      - i-network

  #restart : no always on-failure unless-stopped
  