version: '3.3'

services:
  mariadb_asalek:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - ~/home/asalek/Desktop
    restart: always
    env_file:
      - .env
  nginx_asalek:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    depends_on:
      - mariadb_asalek

  #restart : no always on-failure unless-stopped
  